GET http://localhost:3000
###
GET http://localhost:3000/employee
###
GET http://localhost:3000/employee/3
###
POST http://localhost:3000/employee HTTP/2
Content-Type: application/json

{
  "name": "Irwin",
  "department": "Engineering Team",
  "city": "Bekasi",
  "email": "irwin@infradigital.io"
}
### 
PUT http://localhost:3000/employee/1 HTTP/2
Content-Type: application/json

{
  "name": "Asad",
  "department": "Engineering Team",
  "city": "Jakarta",
  "email": "asad@infradigital.io"
}
###
DELETE http://localhost:3000/employee/3 HTTP/2

### GET ALL PERFORMANCE REVIEW
GET http://localhost:3000/performance-review 

### GET PERFORMANCE REVIEW BY ID
GET http://localhost:3000/performance-review/2

### GET PERFORMANCE REVIEW BY EMPLOYEE ID
GET http://localhost:3000/performance-review/employee-id/1

### CREATE PERFORMANCE REVIEW
POST http://localhost:3000/performance-review
Content-Type: application/json

{
  "target_employee_id": 2,
  "reviewer_ids": [4,1]
}
